import {
  type StatesSort,
  type StatesFilters,
  curateStates,
  STATES_SORT,
} from "./states";
import {
  type SupportGroupsFilters,
  type SupportGroupsSort,
  curateSupportGroups,
  SUPPORT_GROUPS_SORT,
} from "./supportgroup";
import {
  type ProfessionalsFilters,
  type ProfessionalsSort,
  PROFESSIONALS_SORT,
  curateProfessionals,
} from "./professionals";

export const SORT_ORDER = ["asc", "desc"] as const;
export type SortOrder = (typeof SORT_ORDER)[number];

export const STATE_NAMES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
] as const;

export type StateName = (typeof STATE_NAMES)[number];

export {
  type StatesSort,
  type StatesFilters,
  type ProfessionalsFilters,
  type ProfessionalsSort,
  type SupportGroupsFilters,
  type SupportGroupsSort,
  SUPPORT_GROUPS_SORT,
  STATES_SORT,
  curateStates,
  PROFESSIONALS_SORT,
  curateProfessionals,
  curateSupportGroups,
};
